export const PlanetActions = {
  LOAD_PLANET: "LOAD_PLANET",
  LOAD_PLANET_SUCCESS: "LOAD_PLANET_SUCCESS",
  LOAD_PLANET_ERROR: "LOAD_PLANET_ERROR",
  TOGGLE_MENU: "TOGGLE_MENU",
  HIDDEN_MENU: "HIDDEN_MENU",
};
